csi-addons/volume-replication-operator

.github/workflows/golangci-lint.yaml

gactions: Add golangci-lint linter CI

---

.github/workflows/test.yaml

gactions: Add make test CI

---

go.mod
pkg/client/fake/replication-client.go
pkg/client/replication-client.go
pkg/client/replication-client_test.go

Added Mock client for replication and also the unit testing for the same.

Add unit testing for replication client

---

controllers/volumereplication_controller.go

Get VRC and verify driver

---

controllers/pvc_test.go
controllers/volumereplication_controller.go
controllers/volumereplicationclass.go
controllers/volumereplicationclass_test.go

Implement a func to get the volume replica class and write the unit test to test it.

VR: Change Get VRC to an func and add test

---

controllers/tasks/replication/demote.go
controllers/tasks/replication/disable.go
controllers/tasks/replication/enable.go
controllers/tasks/replication/promote.go
controllers/tasks/replication/resync.go
controllers/tasks/task.go
controllers/volumereplication_controller.go

The controller will create and run a set of tasks required to reach the desired state.
Each task is a small unit of work to be done by controller and can be run in parallel.

Setting up scaffold for controller tasks and invoking them from controller

---

.github/workflows/docker-push.yaml
Makefile

Add GitHub actions CI to build and push images to the quay in an automated fashion.

gaction: Add make docker-build CI

---

controllers/tasks/replication/demote.go

task: Fix alignment of args in DemoteVolume

---

controllers/tasks/replication/enable.go
controllers/tasks/replication/promote.go
controllers/volumereplication_controller.go

As part of the PR, implemented `enable` and `promote` tasks and perform these tasks when the image state is set to primary.

Implement Enable volume replication state

---

controllers/tasks/replication/resync.go
controllers/volumereplication_controller.go

define and run a set of tasks required to resync the volume

adds resync task

---

controllers/tasks/replication/promote.go
controllers/volumereplication_controller.go
pkg/client/fake/replication-client.go
pkg/client/replication-client.go
pkg/client/replication-client_test.go

Added missing force option to the promote volume request.

add force option to promote volume

---

README.md

Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

add useful information to README

---

controllers/tasks/task.go
controllers/volumereplication_controller.go

Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

enable forced volume promotion in case of known errors

---

README.md
api/v1alpha1/volumereplication_types.go
config/crd/bases/replication.storage.openshift.io_volumereplications.yaml
controllers/volumereplication_controller.go

rename imageState to replicationState in the volumeReplication spec

---

controllers/volumereplication_controller.go

Update status of volume replication CR

vr: Update status of the volumereplication object

---

controllers/volumereplication_controller.go

If spec.dataSource.kind, spec.replicationState is not correct there is
no need to requeue it again. As recocile will always fails unless user
changes spec.

VR: return err as nil when requeue not required without spec change

---

controllers/volumereplication_controller.go

Replication was only enabled with Primary Replicaiton State. CR could be created with other states as well, like `Secondary`. This PR enables replication on the every  reconcile.

enable volume replication on every reconcile

---

controllers/secret.go
controllers/volumereplication_controller.go

As part of this commit did below enhancements
- Add VRName in the logs at all places
- Add other object name at places where ever possible
- Add uniformity in the logs

VR: Enhance logging of whole operator

---

controllers/pvc.go
controllers/pvc_test.go
controllers/secret.go
controllers/volumereplication_controller.go
controllers/volumereplicationclass.go
controllers/volumereplicationclass_test.go

VR: Pass custom logger to all funcs of controller

---

controllers/volumereplication_controller.go

This PR addes "NotFound" as a known error for disabling volume replication task. VR is deleted if the volume is not found.

continue with VR object deletion if volume is not found

---

go.mod
go.sum

Signed-off-by: Rakshith R <rar@redhat.com>

use github.com/csi-addons/spec v0.1.0 release

---

.mergify.yml

adding mergify rules to auto-merge PR's when having certain approvals.

ci: add mergify rules for the repo

---

.github/workflows/codespell.yaml
.mergify.yml
controllers/secret.go
pkg/client/replication-client.go
pkg/config/config.go

added GitHub action to check code spell.
TODO: will update mergify rules once #78 is merged.

ci: add codespell github action

---

.github/workflows/golangci-lint.yaml
.mergify.yml

as the quotes are not required in the mergify rules, removing the same.

ci: remove quotes in mergify base rule

---

.mergify.yml

the job names need to be added as conditions to get PR auto-merge.
Ref https://docs.mergify.io/conditions/#github-actions

ci: update mergify conditions

---

.mergify.yml

go version is also added as part of the github status. updating mergify rules for the same.

ci: add go version to mergify condition

---

controllers/status.go

Signed-off-by: Raghavendra Talur <raghavendra.talur@gmail.com>

fix a typo

---

controllers/volumereplication_controller.go

This reverts #94. More discussions on https://github.com/csi-addons/volume-replication-operator/issues/100

Revert "replication: disable replication if its primary state"

---

main.go

skipping the stack trace while logging by default and add configuration to print the timestamp in logging.
`
{"level":"error","ts":1629187039.095559,"logger":"controller-runtime.manager.controller.volumereplication","caller":"controller/controller.go:235","msg":"Reconciler error","reconciler group":"replication.storage.openshift.io","reconciler kind":"VolumeReplication","name":"pvc-volumereplication-ss","namespace":"default","error":"VolumeReplicationClass.replication.storage.openshift.io \"rbd-volumereplicationclass\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg …

replication: skip stacktrace by default

---

controllers/volumereplication_controller.go

refractor waitForVolumeReplicationResource to avoid if/else loops to keep the code simple.

replication: refractor waitForVolumeReplicationResource

---

README.md
api/v1alpha1/volumereplication_types.go
config/crd/bases/replication.storage.openshift.io_volumereplications.yaml
controllers/replication/replication.go
controllers/volumereplication_controller.go
go.mod
go.sum
pkg/client/fake/replication-client.go
pkg/client/replication-client.go
pkg/client/replication-client_test.go

clean version of https://github.com/csi-addons/volume-replication-operator/pull/115

add replication id

---

.mergify.yml

adding a more strict check to consider the requested review changes before merging the PR.

ci: check requested review before merging PR

---

.github/workflows/golangci-lint.yaml
controllers/parameters.go
controllers/pvc.go
controllers/secret.go
controllers/status.go
controllers/strings.go
controllers/suite_test.go
controllers/volumereplication_controller.go
controllers/volumereplicationclass.go
controllers/volumereplicationclass_test.go
pkg/client/replication-client_test.go

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

Remove unnecessary type conversion in the reconciler result 

---

controllers/replication/replication.go
pkg/client/replication-client.go

Fixed code to consider the force flag when sending the request for the csi-driver.
cc @ShyamsundarR

fix: consider force flag for resync
