csi-addons/volume-replication-operator

Dockerfile
controllers/volumereplication_controller.go
main.go
pkg/config/config.go

This PR does below changes
* Add New DriverConfig structure which holds the required information to establish the connection with CSI driver
* dynamic generation of  leader election ID 
* Add leader election Namespace
* Change health-probe-bind-address to `9998`
* Disable Metrics by default

Add new driver specific configurations

---

controllers/parameters.go
controllers/secret.go
controllers/tasks/replication/parameters.go
controllers/volumereplication_controller.go
pkg/client/client.go
pkg/client/fake/replication-client.go
pkg/client/replication-client.go
pkg/client/replication-client_test.go

Added functionality to get the parameters and secrets from the volume replication class and call the RPC DemoteVolume.

Implement DemoteVolume RPC calls.

---

.github/workflows/test-and-build.yaml

Run `make docker-build` it will run `make test` as well. This way we can
run tests and make sure build are working. It will make sure that we can
create buids after merging a PR.

gactions: Run tests and make build

---

controllers/strings.go
controllers/tasks/replication/disable.go
controllers/volumereplication_controller.go

added finalizer for the volumeReplication cr. When the cr is deleted, reconciler will first disable the replication and then remove the finalizer.

adds disable task on CR deletion

---

controllers/tasks/replication/demote.go
controllers/tasks/replication/disable.go
controllers/tasks/replication/enable.go
controllers/tasks/replication/promote.go
controllers/tasks/replication/resync.go
controllers/tasks/task.go
controllers/volumereplication_controller.go

when we are all the tasks from the controller, the controller has to take few decisions based on the response received from the particular tasks. For example, the controller needs to add the Resync or Secondary volume request to the queue so that it is to wait till the resync is completed and the volume is to be marked as ready to use by application pods.

task: Return error and response from the task

---

api/v1alpha1/volumereplication_types.go
controllers/volumereplication_controller.go

Dropping the idea of arrays of tasks for now as it seems we have a unique requirement for each task.
This PR enables automatic re-syncing of volume until response.Ready is true. 
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

enable requeue for resync task when volume is not ready

---

Dockerfile

updated base image from `gcr.io/distroless/static:nonroot` to `gcr.io/distroless/static:latest`
which is commonly used in all CSI sidecar image which allows for GRPC communication
using `gcr.io/distroless/static:nonroot` is blocking the GRPC client to connect to the GRPC server.

update base container image in dockerfile

---

main.go

adding volume-replication to the leader election ID to make it unique for volume replication operator.

add volume-replication to the leader election ID

---

controllers/secret.go

getSecret was returning secret.StringData of type map[string]string
which does not have a secret key. Secret key is present in the
secret.Data of type map[string][]byte.
Fix the getSecret func via returning secret.Data
and converting it to the map[string]string

VR: Fix error "provided secret is empty"

---

.gitignore
controllers/volumereplication_controller.go

As of now reconcile method have very few logs. Which does not really help in case of failures. Add more logs to address the same.

VR: Add more log message in reconcile

---

controllers/volumereplication_controller.go

ResyncVolumeResponse is sent as a pointer we need to convert it back as a pointer to avoid conversion issue.

fix type conversion for resync response

---

controllers/volumereplication_controller.go

Updating status subresource from operator reque the recocile request
again which cause the recocile twice for the same request. Fix the
issue using predicate.
reference:
https://github.com/kubernetes-sigs/kubebuilder/issues/618#issuecomment-698018831

VR: Use predicate to stop reconcile on status subresource update

---

controllers/volumereplication_controller.go

markVolumeAsPrimary was not returning an error when we have an error
which is not known to us. Because of which we were getting nil in
recocile and updating the status of the VR to primary.

VR: Fix markVolumeAsPrimary to return err in case of !isKnownError

---

.github/workflows/docker-push.yaml
.github/workflows/test-and-build.yaml
Makefile
PROJECT
README.md
controllers/pvc_test.go
controllers/suite_test.go
controllers/tasks/replication/parameters.go
controllers/volumereplication_controller.go
controllers/volumereplicationclass.go
controllers/volumereplicationclass_test.go
go.mod
go.sum
main.go
pkg/client/fake/replication-client.go
pkg/client/replication-client.go
pkg/client/replication-client_test.go

as the org name is changed from kube-storage to csi-addons. rename is done for the same.

rename kube-storage to csi-addons

---

controllers/volumereplication_controller.go

When volume is demoted but  is not ready,  the Status.State is still showing image as primary until the volume is ready. This creates confusion.  This PR changes the Status.State to secondary when volume is demoted but volume is not ready.

fix status.state when volume is demoted but not ready

---

controllers/status.go

This PR adds 'ResyncTriggered' condition when resync is triggered but volume is not ready to use

fix status conditions when resync triggered but volume is not ready to use

---

.github/workflows/docker-publish.yaml
Makefile

updated Makefile to accept the IMG_NAME and IMG_TAG as parameters when building and pushing the docker image and also added a GitHub action to push the image based on the release tag to the quay.io

Add github action to push docker image for released tags

---

controllers/status.go
controllers/volumereplication_controller.go

when there is a request to mark the volume as secondary, First demote the image and then requeue the request with a delay of `15 seconds`. This delay is introduced because some storage system needs some time to identify the volume needs resync
or not, when the Reconcile happens again it will demote the volume and then sends a request to check the volume needs resync or not.

requeue the request if the volume is marked as secondary

---

.mergify.yml

added mergify rule to backport PR based on the label to a release branch.

ci: add mergify rule to backport PR

---

api/v1alpha1/volumereplication_types.go
api/v1alpha1/volumereplicationclass_types.go
config/crd/bases/replication.storage.openshift.io_volumereplicationclasses.yaml
config/crd/bases/replication.storage.openshift.io_volumereplications.yaml

As part of the PR made below changes to the custom resource
* Add validation for the spec.state
* Add printcolumn
* Add shortName

Make some enhancements to the volume replication CR

---

controllers/volumereplication_controller.go

if a CR is Secondary, then the assumption is it is Primary somewhere else, or at least there is no conclusive action to actually disable mirroring.
Allowing the Deletion of CR if the image is in a secondary state. and the Replication will be disabled when the VR is deleted on the PVC is in a primary state.
fixes: #91

replication: disable replication if its primary state

---

controllers/volumereplication_controller.go
controllers/volumereplicationclass.go
controllers/volumereplicationclass_test.go

If the PVC/objects are deleted in parallel we can easily assume that the replication is removed as the backend storage is deleted and we can remove the finalizer to garbage collect the VR object.
fixes: #92
fixes: #38

replication: skip disablingReplication if PVC not found

---

.github/workflows/docker-publish.yaml
.github/workflows/docker-push.yaml

this commit avoids running push and publish jobs from the forked repo.

ci: push images only on volume-replication-operator repo

---

go.mod
main.go

One can still get stack trace for Warn and Error levels by running the operator in development mode by setting the env VOL_REP_DEVELOPER true.

Disable stack trace for error and above error level logs

---

controllers/finalizers.go
controllers/volumereplication_controller.go

This PR does below 
* Move VR finalizers logic to a new helper function
* Add PVC finalizer when VR is created
* Remove PVC finalizer when VR is deleted 
updates #100

Add/Delete PVC finalizers for the volume replication

---

.mergify.yml

as part of #107 we have updated the GitHub action to test with golang 1.16 but mergify rules are not updated for the same. This commit updates the mergify rules for golang 1.16

ci: update mergify rules to golang 1.16

---

controllers/volumereplication_controller.go

This PR will allow the volume replication operator to start and not fail when `volumereplicationclasses` and `volumereplications` crds are not in the cluster.
It will wait until they will create.
This PR is related to #97 issue.

wait for volume replication crds

---

controllers/status.go
controllers/volumereplication_controller.go

The condition updates are when processing as secondary
- Resyncing
- Is false on any errors
- Is false if degraded is false
- Is true, if resync is successful and volume is not
yet "ready" to use
- Degraded
- Is true on errors
- Is true UNTIL resync returns "ready" response
- Is false ONLY when resync returns "ready"
As Degraded moves to false, resyncing will move to
false as well, other than cases where there are
errors, or resync status is not yet determined. Resync
status is for example undetermined if we issued a
demote volume request, from markVolAsSecondary.
Resyncing: denotes if resync is active
Degraded: denotes local secondary contents are not
in full sync with remote, and that happens only when
remote is marked Secondary and local is also Secondary
and the final sync is …

Update conditions to reflect degraded and resyncing

---

controllers/volumereplication_controller.go

when the VR is marked as secondary the current instance object still contains the status.State
as primary, not secondary. we need to set the status.State to secondary when the volume is demoted successfully.

replication: set status.State to secondary when VR is marked for secondary

---

controllers/replication/replication.go
controllers/replication/replication_test.go
controllers/volumereplication_controller.go

instead of adding both the GRPC error code and the message to CR status just update the CR with the GRPC error message for better readability.
* Before Fix
```yaml
lastStartTime: "2021-11-30T06:46:52Z"
message: 'rpc error: code = Internal desc = failed to get local status: rbd: ret=-2,
No such file or directory'
observedGeneration: 2
state: Unknown
```
* After Fix
```yaml
lastStartTime: "2021-11-30T06:46:52Z"
message: 'failed to get local status: rbd: ret=-2, No such file or directory'
observedGeneration: 2
state: Unknown
```

replication: add grpc message to CR status

---

.mergify.yml

Mergifyio is deprecating `merge` action, which will be replaced by `queue` action. https://blog.mergify.com/strict-mode-deprecation/
This commit makes necessary changes for the same.

ci: update mergifyio config to use queue action
